In [ ]:
# Polynomial Linear Regression
# It's still linear, because we are talking about the coefficients

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('Position_Salaries.csv')
X = dataset.iloc[:, 1:2].values # now X is a matrix
y = dataset.iloc[:, 2].values

In [ ]:
#from sklearn.model_selection import train_test_split
#train_X, test_X, train_y, test_y = train_test_split(X, y, test_size= , random_state=0)

In [3]:
# fit linear regression
from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression()
lin_reg.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [5]:
# fit polynomial regression
from sklearn.preprocessing import PolynomialFeatures

poly_reg = PolynomialFeatures(degree = 2)
X_poly = poly_reg.fit_transform(X)
print(X_poly)

[[  1.   1.   1.]
 [  1.   2.   4.]
 [  1.   3.   9.]
 [  1.   4.  16.]
 [  1.   5.  25.]
 [  1.   6.  36.]
 [  1.   7.  49.]
 [  1.   8.  64.]
 [  1.   9.  81.]
 [  1.  10. 100.]]


In [ ]:
lin_reg_2 = LinearRegression()
lin_reg_2.fit(X_poly, y)